#theme: jekyll-theme-gitbook
remote_theme: pages-themes/cayman@v0.2.0
#remote_theme: pages-themes/tactile@v0.2.0
plugins: 
  - jekyll-remote-theme
  - jektex
title: Entendiendo dinámica de poblaciones
description: Taller semana enseñanza de las ciencias 2025, FCEyN - UBA.
